<a href="https://colab.research.google.com/github/swathikapendala/BATCH-11/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
df=pd.read_csv("sales.csv")
df.head()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261696,01-12-2021,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4,"$1,252.00","$2,295.00","$4,172.00","$5,008.00","$9,180.00"
1,261695,01-12-2021,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1,"$1,266.00","$2,320.00","$1,054.00","$1,266.00","$2,320.00"
2,261697,02-12-2021,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2,$420.00,$769.00,$698.00,$840.00,"$1,538.00"
3,261698,02-12-2021,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1,$420.00,$769.00,$349.00,$420.00,$769.00
4,261699,03-12-2021,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2,"$1,252.00","$2,295.00","$2,086.00","$2,504.00","$4,590.00"

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (ipython-input-3040106292.py, line 1)